Rails/config/routes.rb
Rails.application.routes.draw do
  resources :qualificacaos
  get "clientes/index"
  get "clientes/show"
  get "clientes/new"
  get "clientes/create"
  get "clientes/edit"
  get "clientes/update"
  get "clientes/destroy"
  resources :pessoas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

Rails/app/models/qualificacao.rb
class Qualificacao < ApplicationRecord
  belongs_to :cliente
  belongs_to :restaurante
end

Rails/app/controllers/qualificacaos_controller.rb
class QualificacaosController < ApplicationController
  before_action :set_qualificacao, only: %i[ show edit update destroy ]

  # GET /qualificacaos or /qualificacaos.json
  def index
    @qualificacaos = Qualificacao.all
  end

  # GET /qualificacaos/1 or /qualificacaos/1.json
  def show
  end

  # GET /qualificacaos/new
  def new
    @qualificacao = Qualificacao.new
  end

  # GET /qualificacaos/1/edit
  def edit
  end

  # POST /qualificacaos or /qualificacaos.json
  def create
    @qualificacao = Qualificacao.new(qualificacao_params)

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: "Qualificacao was successfully created." }
        format.json { render :show, status: :created, location: @qualificacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualificacaos/1 or /qualificacaos/1.json
  def update
    respond_to do |format|
      if @qualificacao.update(qualificacao_params)
        format.html { redirect_to @qualificacao, notice: "Qualificacao was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @qualificacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacaos/1 or /qualificacaos/1.json
  def destroy
    @qualificacao.destroy!

    respond_to do |format|
      format.html { redirect_to qualificacaos_path, notice: "Qualificacao was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacao
      @qualificacao = Qualificacao.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def qualificacao_params
      params.expect(qualificacao: [ :cliente_id, :restaurante_id, :nota, :valor_gasto ])
    end
end

Rails/app/helpers/qualificacaos_helper.rb
module QualificacaosHelper
end

Rails/app/views/qualificacaos/_form.html.erb
<%= form_with(model: qualificacao) do |form| %>
  <% if qualificacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
        <% qualificacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :restaurante_id, style: "display: block" %>
    <%= form.text_field :restaurante_id %>
  </div>

  <div>
    <%= form.label :nota, style: "display: block" %>
    <%= form.text_field :nota %>
  </div>

  <div>
    <%= form.label :valor_gasto, style: "display: block" %>
    <%= form.text_field :valor_gasto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/app/views/qualificacaos/_qualificacao.html.erb
<div id="<%= dom_id qualificacao %>">
  <p>
    <strong>Cliente:</strong>
    <%= qualificacao.cliente_id %>
  </p>

  <p>
    <strong>Restaurante:</strong>
    <%= qualificacao.restaurante_id %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= qualificacao.nota %>
  </p>

  <p>
    <strong>Valor gasto:</strong>
    <%= qualificacao.valor_gasto %>
  </p>

</div>

Rails/app/views/qualificacaos/edit.html.erb
<% content_for :title, "Editing qualificacao" %>

<h1>Editing qualificacao</h1>

<%= render "form", qualificacao: @qualificacao %>

<br>

<div>
  <%= link_to "Show this qualificacao", @qualificacao %> |
  <%= link_to "Back to qualificacaos", qualificacaos_path %>
</div>

Rails/app/views/qualificacaos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Qualificacaos" %>

<h1>Qualificacaos</h1>

<div id="qualificacaos">
  <% @qualificacaos.each do |qualificacao| %>
    <%= render qualificacao %>
    <p>
      <%= link_to "Show this qualificacao", qualificacao %>
    </p>
  <% end %>
</div>

<%= link_to "New qualificacao", new_qualificacao_path %>

Rails/app/views/qualificacaos/new.html.erb
<% content_for :title, "New qualificacao" %>

<h1>New qualificacao</h1>

<%= render "form", qualificacao: @qualificacao %>

<br>

<div>
  <%= link_to "Back to qualificacaos", qualificacaos_path %>
</div>

Rails/app/views/qualificacaos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @qualificacao %>

<div>
  <%= link_to "Edit this qualificacao", edit_qualificacao_path(@qualificacao) %> |
  <%= link_to "Back to qualificacaos", qualificacaos_path %>

  <%= button_to "Destroy this qualificacao", @qualificacao, method: :delete %>
</div>