Ruby/rails/restaurante/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :pessoas
  resources :restaurantes
  resources :restaurante
  
  get "up" => "rails/health#show", as: :rails_health_check


  
end

Ruby/rails/restaurante/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Ruby/rails/restaurante/app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :qualificacoes

    validate :nome,
            presence: {message: "nome deve ser preenchido"},
            uniqueness: {message: "nome ja cadastrado"}

    validate :idade,
            numericality: {
                greater_than: 0,
                less_than: 100,
                message: "deve ser um numero entre 0 e 99"
            }
end

Ruby/rails/restaurante/app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

Ruby/rails/restaurante/app/models/prato.rb
# app/models/prato.rb

class Prato < ApplicationRecord

  has_and_belongs_to_many :restaurantes
  has_one :receita

  validates :nome,
            presence: { message: "do prato deve ser preenchido" },
            uniqueness: { message: "do prato já cadastrado" }

  validate :validate_presence_of_more_than_one_restaurante

  private
  
  def validate_presence_of_more_than_one_restaurante
    if restaurantes.empty?
      errors.add(:restaurantes, "deve pertencer a pelo menos um restaurante")
    end
  end
end

Ruby/rails/restaurante/app/models/qualificacao.rb
# app/models/qualificacao.rb

class Qualificacao < ApplicationRecord

  belongs_to :cliente
  belongs_to :restaurante

  # Garante que nota e valor_gasto sejam sempre preenchidos.
  validates :nota, :valor_gasto, presence: { message: "deve ser preenchido" }

  # Validação para o campo :nota
  validates :nota, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 10,
    message: "deve ser um número entre 0 e 10"
  }

  # Validação para o campo :valor_gasto
  validates :valor_gasto, numericality: {
    greater_than: 0,
    message: "deve ser um número maior que 0"
  }

  validates_associated :cliente, :restaurante
end

Ruby/rails/restaurante/app/models/receita.rb
class Receita < ApplicationRecord
    belongs_to :pratos

    validate :prato_id, :conteudo presence: {message: "conteudo prato_id e conteudo devem ser preenchidos"}

    validates_associated :prato
end

Ruby/rails/restaurante/app/models/restaurante.rb
#encoding: utf-8

class Restaurante < ApplicationRecord
    has_many :qualificacoes
    has_and_belongs_to_many :pratos

    validates :nome, :endereco, :especialidade, presence: {message: "Campos nome, esdereço e especialidade nao podem ficar fazios"}

    validates :nome, uniqueness: {
        scope: :endereco,
        message: "já existe um cadastro com esse endereço"
    }
end

Ruby/rails/restaurante/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

Ruby/rails/restaurante/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy!

    respond_to do |format|
      format.html { redirect_to clientes_path, notice: "Cliente was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.expect(cliente: [ :nome, :idade ])
    end
end

Ruby/rails/restaurante/app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: %i[ show edit update destroy ]

  # GET /pessoas or /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1 or /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas or /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: "Pessoa was successfully created." }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1 or /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: "Pessoa was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1 or /pessoas/1.json
  def destroy
    @pessoa.destroy!

    respond_to do |format|
      format.html { redirect_to pessoas_path, notice: "Pessoa was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.expect(pessoa: [ :nome, :data_de_nascimento, :altura ])
    end
end

Ruby/rails/restaurante/app/controllers/restaurante_controller.rb
class RestauranteController < ApplicationController
    def index
        @restaurantes = Restaurante.order :nome
    end
end

Ruby/rails/restaurante/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
    def index 
        render "index"
    end
end

Ruby/rails/restaurante/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/rails/restaurante/app/helpers/clientes_helper.rb
module ClientesHelper
end

Ruby/rails/restaurante/app/helpers/pessoas_helper.rb
module PessoasHelper
end

Ruby/rails/restaurante/app/helpers/restaurante_helper.rb
module RestauranteHelper
end

Ruby/rails/restaurante/app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

Ruby/rails/restaurante/app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Idade:</strong>
    <%= cliente.idade %>
  </p>

</div>

Ruby/rails/restaurante/app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :idade, style: "display: block" %>
    <%= form.number_field :idade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby/rails/restaurante/app/views/clientes/edit.html.erb
<% content_for :title, "Editing cliente" %>

<h1>Editing cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Show this cliente", @cliente %> |
  <%= link_to "Back to clientes", clientes_path %>
</div>

Ruby/rails/restaurante/app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Clientes" %>

<h1>Clientes</h1>

<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
    <p>
      <%= link_to "Show this cliente", cliente %>
    </p>
  <% end %>
</div>

<%= link_to "New cliente", new_cliente_path %>

Ruby/rails/restaurante/app/views/clientes/new.html.erb
<% content_for :title, "New cliente" %>

<h1>New cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Back to clientes", clientes_path %>
</div>

Ruby/rails/restaurante/app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cliente %>

<div>
  <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
  <%= link_to "Back to clientes", clientes_path %>

  <%= button_to "Destroy this cliente", @cliente, method: :delete %>
</div>

Ruby/rails/restaurante/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Restaurante" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby/rails/restaurante/app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa) do |form| %>
  <% if pessoa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
        <% pessoa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :altura, style: "display: block" %>
    <%= form.text_field :altura %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby/rails/restaurante/app/views/pessoas/_pessoa.html.erb
<div id="<%= dom_id pessoa %>">
  <p>
    <strong>Nome:</strong>
    <%= pessoa.nome %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= pessoa.data_de_nascimento %>
  </p>

  <p>
    <strong>Altura:</strong>
    <%= pessoa.altura %>
  </p>

</div>

Ruby/rails/restaurante/app/views/pessoas/edit.html.erb
<% content_for :title, "Editing pessoa" %>

<h1>Editing pessoa</h1>

<%= render "form", pessoa: @pessoa %>

<br>

<div>
  <%= link_to "Show this pessoa", @pessoa %> |
  <%= link_to "Back to pessoas", pessoas_path %>
</div>

Ruby/rails/restaurante/app/views/pessoas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pessoas" %>

<h1>Pessoas</h1>

<div id="pessoas">
  <% @pessoas.each do |pessoa| %>
    <%= render pessoa %>
    <p>
      <%= link_to "Show this pessoa", pessoa %>
    </p>
  <% end %>
</div>

<%= link_to "New pessoa", new_pessoa_path %>

Ruby/rails/restaurante/app/views/pessoas/new.html.erb
<% content_for :title, "New pessoa" %>

<h1>New pessoa</h1>

<%= render "form", pessoa: @pessoa %>

<br>

<div>
  <%= link_to "Back to pessoas", pessoas_path %>
</div>

Ruby/rails/restaurante/app/views/pessoas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pessoa %>

<div>
  <%= link_to "Edit this pessoa", edit_pessoa_path(@pessoa) %> |
  <%= link_to "Back to pessoas", pessoas_path %>

  <%= button_to "Destroy this pessoa", @pessoa, method: :delete %>
</div>

Ruby/rails/restaurante/app/views/restaurante/index.html.erb
<table>
<tr>
<th>Nome</th>
<th>Endereço</th>
<th>Especialidade</th>

</tr>
<% @restaurantes.each do |restaurante| %>
<tr>
<td><%= restaurante.nome %> </td>
<td><%= restaurante.endereco %> </td>
<td><%= restaurante.especialidade %> </td>
</tr>
<% end %>
</table>

Ruby/rails/restaurante/app/views/restaurantes/index.html.erb
<p> Dentro do controller Restaurentes </p>